/* generated by Svelte v4.2.1 */
import { create_ssr_component, each, escape } from "svelte/internal";

const Component = create_ssr_component(($$result, $$props, $$bindings, slots) => {
	let { name = 'world' } = $$props;
	if ($$props.name === void 0 && $$bindings.name && name !== void 0) $$bindings.name(name);

	return `<div>${each([...Array(10).keys()], i => {
		return `<div>${escape(i)}. Hello ${escape(name)}!</div>`;
	})}</div>`;
});

export default Component;