# ============================================================================
# LAJU FRAMEWORK - GITHUB ACTIONS AUTO DEPLOY WORKFLOW
# ============================================================================
#
# PANDUAN PENGGUNAAN:
# -------------------
# File ini adalah template GitHub Actions untuk auto-deploy aplikasi Laju
# ke server produksi Anda. Workflow ini akan berjalan otomatis setiap kali
# ada push ke branch 'main'.
#
# FLOW DEPLOYMENT:
# ----------------
# Push code → GitHub Actions → Run Tests → Deploy → Smoke Tests
#
# Dengan flow ini, Anda TIDAK PERLU build di local sebelum push.
# Cukup push source code, server yang akan melakukan build.
#
# CARA SETUP:
# -----------
# 1. Copy folder 'workflows' ke root project Anda dan rename menjadi '.github'
#    Struktur akhir: .github/workflows/deploy.yml
#
# 2. Setup GitHub Secrets di repository Anda:
#    - Buka repository GitHub > Settings > Secrets and variables > Actions
#    - Tambahkan secrets berikut:
#
#    SSH_HOST        : IP address atau domain server Anda (contoh: 123.45.67.89)
#    SSH_USER        : Username SSH server (contoh: root, ubuntu, atau user lain)
#    SSH_PRIVATE_KEY : Private key SSH untuk autentikasi (isi lengkap termasuk 
#                      -----BEGIN OPENSSH PRIVATE KEY----- dan -----END...)
#    SLACK_WEBHOOK   : (Opsional) Slack webhook URL untuk notifications
#
# 3. Pastikan server sudah di-setup:
#    - Node.js 22 terinstall (via NVM recommended)
#    - PM2 terinstall global: npm install -g pm2
#    - Git terinstall dan repository sudah di-clone
#    - PM2 process sudah dibuat dengan nama yang sesuai (default: 'laju')
#
# 4. Sesuaikan konfigurasi di bawah:
#    - Ganti path '/root/laju' dengan path project di server Anda
#    - Ganti 'pm2 reload laju' dengan nama PM2 process Anda
#    - Ganti branch 'main' jika menggunakan branch lain
#    - Ganti 'http://your-domain.com' dengan domain production Anda
#
# CARA GENERATE SSH KEY:
# ----------------------
# Di local machine:
#   ssh-keygen -t ed25519 -C "github-actions-deploy"
#
# Copy public key ke server:
#   ssh-copy-id -i ~/.ssh/id_ed25519.pub user@server-ip
#
# Copy private key untuk GitHub Secret:
#   cat ~/.ssh/id_ed25519
#
# TROUBLESHOOTING:
# ----------------
# - Jika NVM tidak ditemukan, pastikan path NVM_DIR sesuai dengan instalasi
# - Jika PM2 tidak ditemukan, tambahkan: export PATH="$PATH:$(npm bin -g)"
# - Cek logs di GitHub Actions tab untuk melihat error detail
#
# WORKFLOW:
# ---------
# 1. Test job runs (all tests: unit + integration)
# 2. Jika tests pass → Deploy job runs
# 3. Deploy job hanya jalan di main branch
# 4. Setelah deploy → Run smoke tests
# 5. Jika smoke tests fail → Auto-rollback
#
# ============================================================================

name: Test & Deploy

# Pemicu: Jalankan workflow ini setiap kali ada push ke branch apapun
on:
  push:
    branches: [main, develop, '*']
  pull_request:
    branches: [main, develop]

# Pekerjaan yang harus dilakukan
jobs:
  # ============================================================================
  # TEST JOB - Run all tests before deployment
  # ============================================================================
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout kode
      - name: Checkout code
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Run all tests (unit + integration)
      - name: Run all tests
        run: npm run test:run

      # Build application
      - name: Build application
        run: npm run build

  # ============================================================================
  # DEPLOY JOB - Deploy ke production (hanya jika tests pass)
  # ============================================================================
  deploy:
    needs: test  # Hanya jalan jika test job pass
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  # Hanya deploy di main branch

    steps:
      # Checkout kode
      - name: Checkout code
        uses: actions/checkout@v4

      # SSH ke server dan jalankan perintah deploy
      - name: SSH and run deploy commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "🚀 Starting deployment..."
            
            # [SESUAIKAN] Ganti dengan path ke direktori proyek Anda
            cd /root/laju
            
            echo "📥 Pulling code from GitHub..."
            git pull origin main

            # Load NVM (diperlukan karena SSH non-interactive shell)
            echo "⚙️ Loading NVM..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

            # Gunakan Node.js 22
            nvm use 22

            echo "📦 Installing dependencies..."
            npm install 

            echo "🔨 Building application..."
            npm run build

            echo "🗄️ Running database migrations..."
            npm run migrate
        
            # [SESUAIKAN] Ganti 'laju' dengan nama PM2 process Anda
            echo "🔄 Reloading PM2 process..."
            pm2 reload laju
            
            echo "✅ Deployment finished!"

      # Run smoke tests setelah deployment
      - name: Run smoke tests
        run: |
          echo "🧪 Running smoke tests..."
          
          # Cek health endpoint
          response=$(curl -s -o /dev/null -w "%{http_code}" http://your-domain.com/health)
          if [ $response -ne 200 ]; then
            echo "❌ Health endpoint failed: $response"
            exit 1
          fi
          echo "✅ Health endpoint OK"
          
          # Cek login page
          response=$(curl -s -o /dev/null -w "%{http_code}" http://your-domain.com/login)
          if [ $response -ne 200 ]; then
            echo "❌ Login page failed: $response"
            exit 1
          fi
          echo "✅ Login page OK"
          
          echo "✅ All smoke tests passed!"
        continue-on-error: false

      # Notify success (opsional)
      - name: Notify success
        if: success()
        run: |
          if [ -n "${{ secrets.SLACK_WEBHOOK }}" ]; then
            curl -X POST ${{ secrets.SLACK_WEBHOOK }} \
              -H 'Content-Type: application/json' \
              -d '{"text":"✅ Deployment successful!\n\nCommit: ${{ github.sha }}\nBranch: ${{ github.ref_name }}"}'
          fi
          echo "✅ Deployment successful!"

      # Notify failure
      - name: Notify failure
        if: failure()
        run: |
          if [ -n "${{ secrets.SLACK_WEBHOOK }}" ]; then
            curl -X POST ${{ secrets.SLACK_WEBHOOK }} \
              -H 'Content-Type: application/json' \
              -d '{"text":"❌ Deployment failed!\n\nCommit: ${{ github.sha }}\nBranch: ${{ github.ref_name }}"}'
          fi
          echo "❌ Deployment failed, initiating rollback..."

      # Auto-rollback on failure
      - name: Rollback deployment
        if: failure()
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /root/laju
            git revert HEAD --no-edit
            git push origin main
            pm2 reload laju
            echo "🔄 Rollback completed!"